// Generated by CoffeeScript 1.10.0
(function() {
  "Config values";
  var C;

  C = {};

  _first.offer('config', C);

  C.winSize = {
    'wid': 800,
    'hei': 650
  };

  C.tileSize = 1000;

  C.tileDensity = 1000;

  C.timeStep = 1 / 60.0;

}).call(this);
