// Generated by CoffeeScript 1.10.0
(function() {
  "Config\n\nConfiguration values";
  var C, boomColors, flashColors;

  C = {};

  _first.offer('config', C);

  C.timeStep = 1000 / 60.0;

  C.timePanic = 1000 * 60.0;

  C.winWid = 800;

  C.winHei = 650;

  C.halfWinWid = C.winWid / 2;

  C.halfWinHei = C.winHei / 2;

  C.tileSize = 2000;

  C.tileDensity = 15;

  C.tileCount = Math.floor(C.tileDensity * C.tileSize * C.tileSize / 10000);

  C.spectralTypes = ['A', 'B', 'F', 'K', 'M', 'O'];

  C.baseMass = 10000;

  C.shipAcc = 5 / 1000;

  C.shipRetro = C.shipAcc / 3;

  C.shipAngVel = 2 / 1000;

  C.shipDrag = .1 / 1000;

  C.shipMass = 10;

  C.shipShields = 10;

  C.shipRegen = 0.5 / 1000;

  C.shipBeamCoolDown = 1 * 1000;

  C.beamDamage = 1;

  C.beamRange = 500;

  C.beamDuration = 180;

  C.beamColors = ["rgba(100, 255, 255, 1)", "rgba(  0, 225, 255, 1)", "rgba( 25, 175, 175, 1)", "rgba( 50, 125, 125, 1)", "rgba( 25,  50,  50, 1)", "rgba(  0,   0,   0, 0)"];

  C.beamWidths = [4, 3, 2, 1, 1, 0];

  C.rockAngVel = 2 / 1000;

  C.rockVel = 100 / 1000;

  C.rockRad = 30;

  C.rockRadii = [10, 15, 19, 29, 40];

  C.rockSpawnChance = 3 / 1000;

  C.rockMass = 100;

  C.rockArmor = 5;

  C.rockRegen = 1 / 100;

  C.rockMaxDamage = {
    C: [1.0, 1.0, 1.5, 1.5, 2.0],
    S: [1.0, 1.5, 1.5, 2.0, 2.5],
    M: [1.5, 1.5, 2.0, 2.5, 3.0]
  };

  C.rockBaseColors = {
    C: [[125, 125, 125], [100, 80, 70]],
    S: [[120, 120, 0], [130, 69, 19]],
    M: [[90, 90, 90], [115, 65, 14]]
  };

  C.rockBoomColors = {
    C: [[255, 100, 100], [255, 125, 100]],
    S: [[240, 150, 100], [255, 100, 100]],
    M: [[240, 100, 100], [255, 125, 100]]
  };

  C.rockColor = function(ratio, type, side) {
    var base, boom, colors, i, j;
    base = C.rockBaseColors[type][side];
    boom = C.rockBoomColors[type][side];
    colors = [];
    for (i = j = 0; j < 3; i = ++j) {
      colors.push(Math.floor((boom[i] - base[i]) * ratio + base[i]));
    }
    return "rgba(" + colors[0] + "," + colors[1] + "," + colors[2] + ",1";
  };

  C.boomMaxAge = 250;

  C.boomGrowthRate = 180 / 1000;

  C.boomInitialRadius = 25;

  boomColors = {
    inner: [[235, 255, 255], [245, 255, 255], [255, 255, 255], [255, 245, 245], [255, 225, 225], [245, 200, 200], [235, 160, 160], [225, 120, 120], [200, 75, 75], [150, 25, 25]],
    outer: [[235, 255, 255], [245, 255, 225], [255, 255, 200], [255, 245, 175], [255, 225, 150], [245, 200, 125], [235, 150, 75], [225, 100, 50], [200, 25, 25], [150, 0, 0]]
  };

  C.boomInnerColor = function(ratio) {
    var colors, list;
    list = boomColors.inner;
    colors = list[Math.floor(ratio * list.length)];
    return "rgba(" + colors[0] + "," + colors[1] + "," + colors[2] + "," + (1 - ratio / 2);
  };

  C.boomOuterColor = function(ratio) {
    var colors, list;
    list = boomColors.outer;
    colors = list[Math.floor(ratio * list.length)];
    return "rgba(" + colors[0] + "," + colors[1] + "," + colors[2] + "," + (1 - ratio / 2);
  };

  C.flashMaxAge = 300;

  C.flashShrinkRate = 100 / 1000;

  C.flashInitialRadius = 40;

  flashColors = {
    inner: [[255, 255, 255], [255, 255, 255], [225, 255, 255], [200, 255, 255], [150, 255, 255], [125, 225, 255], [100, 200, 225], [90, 150, 200], [75, 100, 150], [50, 75, 125]],
    outer: [[255, 255, 255], [255, 255, 255], [225, 255, 255], [200, 255, 255], [150, 255, 255], [125, 225, 255], [100, 200, 225], [90, 150, 200], [75, 100, 150], [50, 75, 125]]
  };

  C.flashInnerColor = function(ratio) {
    var colors, list;
    list = flashColors.inner;
    colors = list[Math.floor(ratio * list.length)];
    return "rgba(" + colors[0] + "," + colors[1] + "," + colors[2] + "," + (1 - ratio);
  };

  C.flashOuterColor = function(ratio) {
    var colors, list;
    list = flashColors.outer;
    colors = list[Math.floor(ratio * list.length)];
    return "rgba(" + colors[0] + "," + colors[1] + "," + colors[2] + "," + (1 - ratio);
  };

}).call(this);
