// Generated by CoffeeScript 1.10.0
(function() {
  "The \"Engine\"\n\nThis should dispatch game input, update, and view";
  var C, E, Engine, H, M, S,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  E = {};

  _first.offer('engine', E);

  C = _first.request('config');

  H = _first.request('helper');

  M = _first.request('model');

  S = _first.request('state');

  Engine = (function() {
    Engine.prototype.player = null;

    Engine.prototype.model = null;

    Engine.prototype.state = null;

    Engine.prototype.lastState = null;

    function Engine(ctx) {
      this.ctx = ctx;
      this.bindEvent = bind(this.bindEvent, this);
      this.ctx.canvas.width = C.winWid;
      this.ctx.canvas.height = C.winHei;
      S.initStates(this);
      this.timeStep = C.timeStep;
      this.timePanic = C.timePanic;
      this.bindEvent('keydown');
      this.bindEvent('keyup');
    }

    Engine.prototype.draw = function() {
      "Draw the game state to the canvas";
      return this.state.draw(this.ctx);
    };

    Engine.prototype.update = function(dt) {
      "Update the game state by dt";
      while (dt > this.timeStep) {
        this.state.update(this.timeStep);
        dt = dt - this.timeStep;
        if (dt > this.timePanic) {
          dt = 0;
        }
      }
      return this.state.update(dt);
    };

    Engine.prototype.input = function(type, data) {
      "Handle user input";
      return this.state.input(type, data);
    };

    Engine.prototype.changeState = function(newState) {
      "Change between game states";
      if (this.state) {
        this.state.exit();
        this.lastState = this.state;
      }
      this.state = newState;
      return this.state.enter();
    };

    Engine.prototype.popState = function() {
      if (this.lastState && this.state) {
        this.state.exit();
        this.state = this.lastState;
        return this.state.enter();
      }
    };

    Engine.prototype.bindEvent = function(eventType) {
      return window.addEventListener(eventType, (function(_this) {
        return function(eventData) {
          if (_this.state) {
            return _this.state.input(eventType, eventData);
          }
        };
      })(this));
    };

    return Engine;

  })();

  E.Engine = Engine;

}).call(this);
