// Generated by CoffeeScript 1.10.0
(function() {
  "The \"Engine\"\n\nThis should dispatch game input, update, and view";
  var C, E, Engine, H, L, MODE;

  E = {};

  _first.offer('engine', E);

  C = _first.request('config');

  H = _first.request('helper');

  L = _first.request('loader');

  MODE = {
    'load': 1,
    'splash': 2,
    'play': 2
  };

  Engine = (function() {
    function Engine(ctx) {
      this.ctx = ctx;
      this.mode = 1;
      this.ctx.canvas.width = C.WID;
      this.ctx.canvas.height = C.HEI;
    }

    Engine.prototype.draw = function() {
      "Draw the game state to the canvas";
      var img, key, ref, results, x, y;
      this.ctx.fillStyle = "#000000";
      this.ctx.fillRect(0, 0, this.ctx.canvas.width, this.ctx.canvas.height);
      x = 50;
      y = 50;
      ref = L.img.ship;
      results = [];
      for (key in ref) {
        img = ref[key];
        this.ctx.drawImage(img, x, y);
        x += 30;
        results.push(y += 30);
      }
      return results;
    };

    Engine.prototype.update = function(dt) {
      return "Update the game state by dt";
    };

    Engine.prototype.input = function() {
      return "Handle user input";
    };

    return Engine;

  })();

  E.Engine = Engine;

}).call(this);
