// Generated by CoffeeScript 1.10.0
(function() {
  "Some useful functions and constants";
  var H;

  H = {};

  _first.offer('helper', H);

  H.PI = Math.PI;

  H.TWOPI = H.PI * 2;

  H.HALFPI = H.PI / 2;

  H.distance = function(pos1, pos2) {
    var dx, dy;
    dx = pos2.x - pos1.x;
    dy = pos2.y - pos1.y;
    return sqrt(dx * dx + dy * dy);
  };

  H.collide = function(cir1, cir2) {
    var dr, dx, dy;
    dx = cir2.x - cir1.x;
    dy = cir2.y - cir1.y;
    dr = cir2.r + cir1.r;
    return dx * dx + dy * dy <= dr * dr;
  };

  H.getVec = function(ang) {
    return {
      x: Math.cos(ang, {
        y: Math.sin(ang)
      })
    };
  };

  H.getAng = function(vec) {
    return Math.atan(vec.y, vec.x);
  };

  H.faceAng = function(obj1, obj2) {
    return Math.atan(obj2.y - obj1.y, obj2.x - obj1.x);
  };

  H.randInt = function(max) {
    return Math.floor(Math.random() * max);
  };

  H.getRandomPos = function(xMax, yMax) {
    var pos;
    pos = {};
    pos.x = Math.floor(Math.random() * xMax);
    pos.y = Math.floor(Math.random() * yMax);
    return pos;
  };

  H.remove = function(list, item) {
    var i;
    i = list.indexOf(item);
    if (i !== -1) {
      return list.splice(i, 1);
    }
  };

  H.flipList = function(list) {
    var item, j, l, len;
    l = [];
    for (j = 0, len = list.length; j < len; j++) {
      item = list[j];
      l.push(item);
    }
    return l.reverse();
  };

  H.getRandomListValue = function(list) {
    return list[Math.floor(Math.random() * list.length)];
  };

  H.getRandomObjValue = function(obj) {
    return obj[H.getRandomListValue(Object.keys(obj))];
  };

  H.createCanvas = function() {
    return document.createElement("canvas");
  };

  H.drawImg = function(bot, top, x, y, a) {
    var img;
    bot.save();
    img = top.canvas;
    bot.translate(x, y);
    bot.rotate(-a);
    bot.drawImage(img, -Math.floor(img.width / 2), -Math.floor(img.height / 2));
    return bot.restore();
  };

}).call(this);
