// Generated by CoffeeScript 1.10.0
(function() {
  "This loads images and sound assets.";
  var A, H, L, loadImg, loadImgFolder, thingsLoaded, thingsToLoad;

  L = {};

  _first.offer('loader', L);

  H = _first.request('helper');

  A = _first.request('assets');

  L.img = {};

  L.snd = {};

  thingsToLoad = 0;

  thingsLoaded = 0;

  L.loadingFinished = function() {
    return thingsToLoad === thingsLoaded;
  };

  L.loadAllImgs = function() {
    var folder, i, len, ref, results;
    ref = A.imgFolders;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      folder = ref[i];
      results.push(loadImgFolder(folder));
    }
    return results;
  };

  loadImgFolder = function(folder) {
    var name, ref, results, src;
    if (!A[folder]) {
      console.log("Image folder: " + folder + " not found in assets.");
      return false;
    }
    console.log("Loading " + folder);
    L.img[folder] = {};
    ref = A[folder];
    results = [];
    for (name in ref) {
      src = ref[name];
      results.push(loadImg(folder, name, src));
    }
    return results;
  };

  loadImg = function(folder, name, src) {
    var img;
    thingsToLoad++;
    img = new Image();
    img.src = src;
    return img.onload = function() {
      var ctx;
      ctx = H.createCanvas().getContext('2d');
      ctx.save();
      ctx.translate(img.width, img.height);
      ctx.rotate(H.HALFPI);
      ctx.drawImage(img, 0, 0);
      ctx.restore();
      thingsLoaded++;
      return L.img[folder][name] = ctx.canvas;
    };
  };

  L.createBgImg = function() {
    "create a starfield";
    return L.img.bg = {};
  };

}).call(this);
