// Generated by CoffeeScript 1.10.0
(function() {
  "Asteroids in Coffeescript\nor\nLook Out Space Mice!\n\nThis is a learning project made while learning coffeescript.";
  "Some things learned:\n\n\nTODO:\n\n\nThings to try:\n1) Proper build tools/package managers.\n2) Things other than canvas\n";
  var E, ctx, engine, lastTime, raf, setup, stopToken;

  E = _first.request('engine');

  ctx = null;

  engine = null;

  stopToken = null;

  lastTime = 0;

  setup = function() {
    var $canvas;
    $canvas = $('<canvas>', {
      'id': 'gameCanvas'
    });
    $('#addCanvasHere').append($canvas);
    ctx = $canvas[0].getContext('2d');
    return engine = new E.Engine(ctx);
  };

  raf = function(time) {
    var dt;
    if (time == null) {
      time = 0;
    }
    dt = time - lastTime;
    lastTime = time;
    stopToken = requestAnimationFrame(raf);
    engine.draw();
    return engine.update(dt);
  };

  $(function() {
    console.log("DOM ready");
    _first.applyAllModules();
    setup();
    return raf();
  });

}).call(this);
