// Generated by CoffeeScript 1.10.0
(function() {
  "Model";
  var A, B, C, E, H, M, Model, U, isAlive;

  M = {};

  _first.offer('model', M);

  A = _first.request('assets');

  B = _first.request('beam');

  C = _first.request('config');

  E = _first.request('entity');

  H = _first.request('helper');

  U = _first.request('hud');

  Model = (function() {
    function Model() {
      "Build the initial state.";
      this.player = null;
      this.gameOver = false;
      this.bg = [];
      this.bases = [];
      this.ships = [];
      this.boats = [];
      this.rocks = [];
      this.booms = [];
      this.flashes = [];
      this.shots = [];
      this.loot = [];
      this.hud = [];
      this.player = E.PlayerShip();
      this.ships.push(this.player);
      this.flash(this.player);
      this.rocks.push(new E.RandRock());
      this.bases.push(new E.LuckyBase());
      this.bases.push(new E.BuildBase());
      this.bg.push(new E.BgTile());
      this.hud.push(new U.shipShieldBar(this.player));
      this.hud.push(new U.shipBeamEnergyBar(this.player));
    }

    Model.prototype.getEntityLists = function() {
      return [this.bg, this.bases, this.loot, this.boats, this.shots, this.rocks, this.ships, this.booms, this.flashes, this.hud];
    };

    Model.prototype.clearEntityLists = function() {
      var i, len, list, ref, results;
      ref = this.getEntityLists;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        list = ref[i];
        results.push(list.length = 0);
      }
      return results;
    };

    Model.prototype.update = function(dt) {
      "update by dt";
      var base, dmg, i, item, j, k, l, len, len1, len2, len3, len4, len5, len6, len7, len8, list, loot, m, n, o, p, pt, q, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, rock, ship, shot;
      ref = this.getEntityLists();
      for (i = 0, len = ref.length; i < len; i++) {
        list = ref[i];
        for (j = 0, len1 = list.length; j < len1; j++) {
          item = list[j];
          item.update(dt);
        }
      }
      ref1 = this.ships;
      for (k = 0, len2 = ref1.length; k < len2; k++) {
        ship = ref1[k];
        if (ship.beamTriggered && ship.canFire()) {
          this.fireDisruptor(ship);
          ship.setJustFired();
        }
        if (ship.tracBeamOn) {
          ref2 = this.loot;
          for (l = 0, len3 = ref2.length; l < len3; l++) {
            loot = ref2[l];
            if (ship.canTractor()) {
              pt = ship.tractorRange(loot);
              if (pt) {
                this.tracBeam(ship.pos, pt);
                loot.kill();
                ship.setJustTractored(loot);
              }
            }
          }
        }
        ref3 = this.rocks;
        for (m = 0, len4 = ref3.length; m < len4; m++) {
          rock = ref3[m];
          if (ship.collide(rock)) {
            dmg = Math.abs(ship.bounce(rock));
            if (ship.applyDamage(Math.min(5, dmg * C.rockCollisionDamage))) {
              this.explode(ship);
              ship.kill();
              this.createLifepods(ship);
            }
          }
        }
      }
      ref4 = this.bases;
      for (n = 0, len5 = ref4.length; n < len5; n++) {
        base = ref4[n];
        ref5 = this.rocks;
        for (o = 0, len6 = ref5.length; o < len6; o++) {
          rock = ref5[o];
          if (base.collide(rock)) {
            rock.bounce(base);
          }
        }
      }
      ref6 = this.shots;
      for (p = 0, len7 = ref6.length; p < len7; p++) {
        shot = ref6[p];
        if (shot.damaging) {
          ref7 = this.rocks;
          for (q = 0, len8 = ref7.length; q < len8; q++) {
            rock = ref7[q];
            if (shot.hit(rock)) {
              if (rock.applyDamage(shot.getDamage())) {
                rock.kill();
                this.explode(rock);
                this.calveRock(rock);
                this.createCrystal(rock);
              }
            }
          }
        }
      }
      if (E.spawnRock(dt)) {
        rock = new E.RandRock();
        this.rocks.push(rock);
        this.flash(rock);
      }
      this.shots = _.filter(this.shots, isAlive);
      this.rocks = _.filter(this.rocks, isAlive);
      this.ships = _.filter(this.ships, isAlive);
      this.booms = _.filter(this.booms, isAlive);
      this.loot = _.filter(this.loot, isAlive);
      this.flashes = _.filter(this.flashes, isAlive);
      if (!this.player.alive) {
        return this.gameOver = true;
      }
    };

    Model.prototype.draw = function(ctx) {
      "Draw the model.";
      var entity, i, len, list, ref, results;
      this.player.centerCamera();
      ref = this.getEntityLists();
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        list = ref[i];
        results.push((function() {
          var j, len1, results1;
          results1 = [];
          for (j = 0, len1 = list.length; j < len1; j++) {
            entity = list[j];
            results1.push(entity.draw(ctx));
          }
          return results1;
        })());
      }
      return results;
    };

    Model.prototype.command = function(cmd) {
      if (cmd === 1) {
        return this.player.va = C.shipAngVel;
      } else if (cmd === 2) {
        return this.player.va = -C.shipAngVel;
      } else if (cmd === 3) {
        return this.player.setAcc(C.shipAcc);
      } else if (cmd === 4) {
        return this.player.setAcc(-C.shipRetro);
      } else if (cmd === 5) {
        this.player.activateBeam();
        return this.player.tarBeamOn = false;
      } else if (cmd === 6) {
        return this.player.activateTarBeam();
      } else if (cmd === 11) {
        return this.player.va = 0;
      } else if (cmd === 13) {
        return this.player.setAcc(0);
      } else if (cmd === 99) {
        this.player.kill();
        this.explode(this.player);
        return this.createLifepods(this.player);
      }
    };

    Model.prototype.fireDisruptor = function(ship) {
      return this.shots.push(B.newDisruptor(ship));
    };

    Model.prototype.calveRock = function(rock) {
      var calf, calves, i, len, results;
      calves = E.calveRock(rock);
      if (calves) {
        results = [];
        for (i = 0, len = calves.length; i < len; i++) {
          calf = calves[i];
          results.push(this.rocks.push(calf));
        }
        return results;
      }
    };

    Model.prototype.createCrystal = function(rock) {
      if (E.spawnCrystalCheck(rock)) {
        return this.loot.push(E.newCrystalOnObj(rock));
      }
    };

    Model.prototype.createLifepods = function(ship) {
      var i, len, pod, ref, results;
      ref = E.newLifepodsOnObj(ship);
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        pod = ref[i];
        results.push(this.loot.push(pod));
      }
      return results;
    };

    Model.prototype.explode = function(obj) {
      return this.booms.push(E.newExplosionOnObj(obj));
    };

    Model.prototype.flash = function(obj) {
      return this.flashes.push(E.newFlashOnObj(obj));
    };

    Model.prototype.tracBeam = function(pos1, pos2) {
      return this.flashes.push(B.newTractorBeam(pos1, pos2));
    };

    return Model;

  })();

  M.Model = Model;

  isAlive = function(obj) {
    return obj.alive;
  };

}).call(this);
