// Generated by CoffeeScript 1.10.0
(function() {
  "Model";
  var A, C, E, Es, H, M, Model;

  M = {};

  _first.offer('model', M);

  A = _first.request('assets');

  C = _first.request('config');

  E = _first.request('entity');

  Es = _first.request('entities');

  H = _first.request('helper');

  Model = (function() {
    Model.prototype.player = null;

    Model.prototype.bases = [];

    Model.prototype.ships = [];

    Model.prototype.rocks = [];

    Model.prototype.booms = [];

    Model.prototype.shots = [];

    Model.prototype.loot = [];

    function Model() {
      ({
        init: function() {
          return "Build the initial state.";
        }
      });
    }

    Model.prototype.draw = function(ctx) {
      return "Draw the model.";
    };

    return Model;

  })();

}).call(this);
