// Generated by CoffeeScript 1.10.0
(function() {
  "State\n\nVarious game states/modes/screens/views/etc.\neg: Preloader Screen, Splash Screen, Play Screen, etc.";
  var A, C, H, M, S, State, changeState, currentState, eng, getCtx, getModel, getPlayer, getState;

  S = {};

  _first.offer('state', S);

  A = _first.request('assets');

  C = _first.request('config');

  H = _first.request('helper');

  M = _first.request('model');

  eng = null;

  S.initStates = function(engine) {
    eng = engine;
    return eng.changeState(S.preload);
  };

  changeState = function(state) {
    return eng.changeState(state);
  };

  getPlayer = function() {
    return eng.player;
  };

  getModel = function() {
    return eng.model;
  };

  getState = function() {
    return eng.state;
  };

  getCtx = function() {
    return eng.ctx;
  };

  State = (function() {
    function State() {
      return;
    }

    State.prototype.enter = function() {
      return console.log("enter");
    };

    State.prototype.draw = function(ctx) {
      return console.log("draw " + ctx);
    };

    State.prototype.update = function(dt) {
      return false;
    };

    State.prototype.input = function(type, data) {
      return console.log("input: " + type + " " + data);
    };

    State.prototype.exit = function() {
      return console.log("exit");
    };

    return State;

  })();

  currentState = null;

  S.setState = function(state) {
    if (currentState) {
      currentState.exit();
    }
    state.enter();
    return currentState = state;
  };

  S.updateState = function(dt) {
    if (currentState) {
      return currentState.update(dt);
    }
  };

  S.preload = {
    enter: function() {
      console.log("enter preload");
      return A.loadAllImgs();
    },
    draw: function(ctx) {
      var text, w;
      ctx.fillStyle = "#000000";
      ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
      text = "Loading";
      ctx.fillStyle = "#FFFFFF";
      ctx.font = '30px Arial';
      w = (ctx.measureText(text)).width / 2;
      return ctx.fillText(text, Math.floor(ctx.canvas.width / 2) - w, Math.floor(ctx.canvas.height / 2) - 15);
    },
    update: function(dt) {
      if (A.loadingFinished()) {
        A.createBgTiles();
        return changeState(S.splash);
      }
    },
    input: function(type, data) {
      console.log("input: " + type + " " + data);
      console.log(type);
      return console.log(data);
    },
    exit: function() {
      return console.log("exit preload");
    }
  };

  S.splash = {
    y: 0,
    enter: function() {
      return console.log("enter splash");
    },
    draw: function(ctx) {
      var a, img;
      ctx.fillStyle = "#000000";
      ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
      H.drawImg(ctx, A.img.bg.tile, ctx.canvas.width / 2, ctx.canvas.height / 2 + this.y);
      H.drawImg(ctx, A.img.bg.tile, ctx.canvas.width / 2, ctx.canvas.height / 2 + this.y - C.tileSize);
      img = A.img.ship.dropciv;
      a = H.HALFPI;
      return H.drawImg(ctx, img, ctx.canvas.width / 2, ctx.canvas.height / 2, a);
    },
    update: function(dt) {
      this.y = this.y + dt / 1.5;
      return this.y = this.y % C.tileSize;
    },
    input: function(type, data) {
      if (type === "keydown") {
        console.log(data.code);
        if (data.code === "Space") {
          return changeState(S.play);
        }
      }
    },
    exit: function() {
      return console.log("exit splash");
    }
  };

  S.play = {
    player: null,
    model: null,
    enter: function() {
      console.log("enter play");
      return this.model = new M.Model();
    },
    draw: function(ctx) {
      ctx.fillStyle = "#000000";
      ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);
      if (this.model) {
        return this.model.draw(ctx);
      }
    },
    update: function(dt) {
      if (this.model) {
        return this.model.update(dt);
      }
    },
    input: function(type, data) {
      console.log(data);
      if (type === "keydown") {
        if (data.code === "ArrowLeft") {
          return this.model.command(1);
        } else if (data.code === "ArrowRight") {
          return this.model.command(2);
        } else if (data.code === "ArrowUp") {
          return this.model.command(3);
        } else if (data.code === "ArrowDown") {

        }
      } else if (type === "keyup") {
        if (data.code === "ArrowLeft") {
          return this.model.command(11);
        } else if (data.code === "ArrowRight") {
          return this.model.command(11);
        } else if (data.code === "ArrowUp") {
          return this.model.command(13);
        } else if (data.code === "ArrowDown") {
          return this.model.command(13);
        }
      }
    },
    exit: function() {
      return console.log("exit play");
    }
  };

  S.gameOver = {
    enter: function() {
      return console.log("enter gameOver");
    },
    draw: function(ctx) {
      return console.log("draw " + ctx);
    },
    update: function(model) {
      return console.log("update " + model);
    },
    input: function(type, data) {
      return console.log("input: " + type + " " + data);
    },
    exit: function() {
      return console.log("exit gameOver");
    }
  };

}).call(this);
